// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t1708ENewWeb.Models;

namespace t1708ENewWeb.Migrations
{
    [DbContext(typeof(t1708ENewWebContext))]
    partial class t1708ENewWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("t1708ENewWeb.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentsRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.Property<string>("SubjectRollNumber");

                    b.HasKey("Id");

                    b.HasIndex("StudentsRollNumber");

                    b.ToTable("Marks");

                    b.HasData(
                        new { Id = 1, SubjectMark = 100, SubjectName = "php", SubjectRollNumber = "123" },
                        new { Id = 2, SubjectMark = 100, SubjectName = "Asp.net", SubjectRollNumber = "123" }
                    );
                });

            modelBuilder.Entity("t1708ENewWeb.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdateAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "123", CreateAt = new DateTime(2018, 11, 6, 19, 1, 5, 353, DateTimeKind.Local), Email = "binhaibin123@gmail.com", FirstName = "hai", LastName = "hai", Status = 1, UpdateAt = new DateTime(2018, 11, 6, 19, 1, 5, 354, DateTimeKind.Local) },
                        new { RollNumber = "124", CreateAt = new DateTime(2018, 11, 6, 19, 1, 5, 354, DateTimeKind.Local), Email = "anhanh@gmail.com", FirstName = "anh", LastName = "anh", Status = 1, UpdateAt = new DateTime(2018, 11, 6, 19, 1, 5, 354, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("t1708ENewWeb.Models.Mark", b =>
                {
                    b.HasOne("t1708ENewWeb.Models.Student", "Students")
                        .WithMany("Marks")
                        .HasForeignKey("StudentsRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
